meta_product_name: "Portfolio"
meta_title: "Estelle Rambur - Portfolio Web developer & Graphic Designer "
meta_description: "All my projects as a Graphic designer and Web developer Front-End. Design, Photo, Coding."
meta_image: "meta-tag-image.png" # should exist in `app/assets/images/`
